### PR TITLE
Fix unsupported parameter and options about lb-rule

### LINKED ISSUE #46: Unsupported argument / unexpected protocol errors
running this code - 
```
module "kubernetes-lb" {   
  source              = "Azure/loadbalancer/azurerm"
  resource_group_name = azurerm_resource_group.kubernetes.name
  name                = "kubernetes-lb"
  pip_name            = "kubernetes-pip"
  lb_sku              = "Standard"
  pip_sku             = "Standard"


  lb_port = {
    http = ["80", "Tcp", "80"]
  }

  lb_probe = {
    http = ["Tcp", "80", ""]
  }

  depends_on = [azurerm_resource_group.kubernetes]
}
```

I am getting the following errors 

```
╷
Error: expected protocol to be one of [All Tcp Udp], got tcp
 
   with module.kubernetes-lb.azurerm_lb_nat_rule.azlb,
   on .terraform/modules/kubernetes-lb/main.tf line 47, in resource "azurerm_lb_nat_rule" "azlb":
   47:   protocol                       = "tcp"


 Error: Unsupported argument
   on .terraform/modules/kubernetes-lb/main.tf line 56, in resource "azurerm_lb_probe" "azlb":
   56:   resource_group_name = data.azurerm_resource_group.azlb.name
 
 An argument named "resource_group_name" is not expected here.
```

These are both errors caused by mismatches between the code here and what is expected by the provider. 

Is this repo still maintained?

### PR DESCRIPTION
**Pull request by Izual750**
Fixes #46 

Changes proposed in the pull request:

- Update "tcp" to "Tcp" on azurerm_lb_nat_rule
- Remove unneeded "resource_group_name" on  azurerm_lb_probe
- Udpate "backend_address_pool_id" on azurerm_lb_rule to have a list of one element.

### CODE REVIEW

**Comment by mahshaban95** [comment]
Hello, when is this PR gonna be merged?
I have noticed that the latest commit to the master branch is 2 years ago. So, is there a plan that this module is gonna be maintained in the future? Should we move to another module or just use Terraform resources directly?

**Comment by Izual750** [comment]
> Hello, when is this PR gonna be merged? I have noticed that the latest commit to the master branch is 2 years ago. So, is there a plan that this module is gonna be maintained in the future? Should we move to another module or just use Terraform resources directly?

From my comprehension, this module is not maintained anymore. I personally tried to write a "home-made" module even if it cover far less use-case as this one used to cover :/

**Comment by lonegunmanb** [comment]
Sorry @Izual750 for this late reply and thanks for your contribution, we're working on a project name Azure Verified Module, and we've converted some legacy modules like [terraform-azurerm-aks](https://github.com/Azure/terraform-azurerm-aks), [terraform-azurerm-vnet](https://github.com/Azure/terraform-azurerm-vnet), [terraform-azurerm-compute](https://github.com/Azure/terraform-azurerm-compute), [terraform-azurerm-network](https://github.com/Azure/terraform-azurerm-network) to our "Verified" standard, adding a new CI pipeline to ensure the code quality, fixing e2e tests and cleaning all remaining issues and pull requests. Due to the limit of our bandwidth, we were not able to convert all legacy modules ASAP, but I promise you that I'll review this pr in this week.

Again, thanks you for opening this pr!

**Review by lonegunmanb — APPROVED** [review]
Thanks @Izual750 , LGTM!

**Pull request merged**
