### PR TITLE
Add private option for loadbalancer

### PR DESCRIPTION
**Pull request by lbnjma**
```hcl
module "mylb" {
  source                                  = "Azure/loadbalancer/azurerm"
  type                                    = "private"
  frontend_subnet_id                      = "MySubnetID"
  frontend_private_ip_address_allocation  = "Static"
  frontend_private_ip_address             = "MyAddressIP"
  
  ...
```

Default `type = public`
Default `frontend_private_ip_address_allocation = "Dynamic"`

### CODE REVIEW

**Comment by lbnjma** [comment]
Hello @dcaro @dtzar ,

Is it possible to have a review please ?

Thanks.

**Comment by dcaro** [comment]
@lbnjma I was oof last week, looking at it now.

**Comment by dtzar** [comment]
@lbnjma Sorry for the extremely long delay in reviewing this one!  Per @dcaro above comment, I thought he had it.  I didn't test it, but it looks good to me.

**Comment by dtzar** [comment]
@jeffreyCline Can you check to make sure the examples work and 
@lbnjma - can you please do a `rake format` to fix the styling?  See: https://github.com/Azure/terraform-test

**Comment by jeffreyCline** [comment]
@lbnjma Since you are adding new options to the module this needs to be reflected in the README.md file. Can you document the changes and add sample usage cases?

**Comment by lbnjma** [comment]
@dtzar Thanks for the review, I've fixed the styling
@jeffreyCline I've updated the documentation, let me know if something is wrong.

**Comment by jeffreyCline** [comment]
@lbnjma It looks like my changes have conflicted with your update to the readme file. Can you resolve the conflicts?

**Pull request merged**
