### PR TITLE
terraform upgrade to v0.12

### PR DESCRIPTION
**Pull request by yupwei68**
terraform upgrade to v0.12

### CODE REVIEW

**Comment by ausfestivus** [comment]
Paging @dtzar can we have this PR approved please?

**Comment by ausfestivus** [comment]
@mybayern1974  any idea who can approve a merge into master?

**Comment by sbbsf** [comment]
@dtzar any chances for merge?

**Comment by sbugalski** [comment]
@dtzar any chances for merge?

**Comment by dtzar** [comment]
I'm not authorized anymore to merge to master. @mybayern1974 ?

**Comment by MihaiAnei** [comment]
Ping!? :( I feel like the Azure terraform modules are ignored lately. I'd rather contribute to the official public ones than make ones "in-house". Can we get at least a status update on what's going on, when this will be merged in, expected activity on the tf-modules?

**Comment by dtzar** [comment]
@rguthriemsft @grayzu ?

**Comment by mybayern1974** [comment]
Sorry for the late response. approved and merged.

**Pull request merged**
